---
- name: Create temp dir
  ansible.builtin.tempfile:
    state: directory
  register: tempdir

- name: Download debs
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ tempdir.path }}/{{ item.name }}.deb"
    mode: "0644"
  loop: "{{ debs }}"

- name: Install debs
  ansible.builtin.apt:
    deb: "{{ tempdir.path }}/{{ item.name }}.deb"
  loop: "{{ debs }}"

- name: Remove temp dir
  ansible.builtin.file:
    state: absent
    path: "{{ tempdir.path }}"
