---
- name: Install apt packages
  ansible.builtin.import_tasks: apt.yaml
- name: Install snap packages
  ansible.builtin.import_tasks: snap.yaml
- name: Install deb pacakges
  ansible.builtin.import_tasks: deb.yaml
  when: install_debs

- name: Install archived packages
  ansible.builtin.import_tasks: archives.yaml
