---
- name: Install snap packages
  community.general.snap:
    name: "{{ item.name }}"
    channel: "{{ item.channel }}"
    classic: "{{ item.classic }}"
    state: present
  loop: "{{ snap_packages }}"
