apt_keys:
  - https://packages.cloud.google.com/apt/doc/apt-key.gpg

apt_registries:
  - deb https://apt.kubernetes.io/ kubernetes-xenial main

apt_pakcages:
  - git
  - python3-pip
  - python3-setuptools
  - virtualenv
  - ssh
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - gnupg
  - kubectl
  - zsh

snap_packages: []

install_debs: false
debs: []

archived_files:
  - name: helm
    url: https://get.helm.sh/helm-v3.8.2-linux-amd64.tar.gz
    binary_path: linux-amd64/helm
  - name: kustomize
    url: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.5.4/kustomize_v4.5.4_linux_amd64.tar.gz
    binary_path: kustomize
